In [21]:
%pip install pandas -q

[notice] A new release of pip is available: 23.0.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [22]:
dataset_name: str = "CB/train.jsonl"

In [23]:
from os.path import abspath, join

dataset_path: str = join(abspath(""), "..", "..", "datasets", dataset_name)
dataset_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/CB/train.jsonl'

In [24]:
from json import loads
from typing import List, Dict, Any

with open(dataset_path, "r") as file:
    records: List[Dict[str, Any]] = [loads(e) for e in file]
print(f"Found {len(records)} records")

Found 250 records

In [25]:
import pandas as pd

dataframe: pd.DataFrame = pd.DataFrame(records)
dataframe.head()

,premise,hypothesis,label,idx
0,It was a complex language. Not written down bu...,the language was peeled down,entailment,0
1,"It is part of their religion, a religion I do ...",no women are allowed to take part in this ritual,entailment,1
2,The Paris to Rouen railway was being extended ...,Gustave was shepherded into creative retreat a...,entailment,2
3,Part of it was to be compulsorily purchased. Y...,Gustave was driven to creative retreat in Croi...,entailment,3
4,"Some of them, like for instance the farm in Co...",buying places is a hobby,entailment,4

In [26]:
len(dataframe)

250

In [27]:
if len(dataframe) >= 500:
    sampled_dataframe: pd.DataFrame = dataframe.sample(n=500)
else:
    sampled_dataframe = dataframe
sampled_dataframe.head()

,premise,hypothesis,label,idx
0,It was a complex language. Not written down bu...,the language was peeled down,entailment,0
1,"It is part of their religion, a religion I do ...",no women are allowed to take part in this ritual,entailment,1
2,The Paris to Rouen railway was being extended ...,Gustave was shepherded into creative retreat a...,entailment,2
3,Part of it was to be compulsorily purchased. Y...,Gustave was driven to creative retreat in Croi...,entailment,3
4,"Some of them, like for instance the farm in Co...",buying places is a hobby,entailment,4

In [28]:
from json import dumps

sampled_records: List[Dict[str, Any]] = sampled_dataframe.to_dict(orient="records")
sampled_records.sort(key=lambda r: r["idx"])
sampled_records_jsonl: List[str] = [dumps(record) for record in sampled_records]
sampled_records_jsonl[0]

'{"premise": "It was a complex language. Not written down but handed down. One might say it was peeled down.", "hypothesis": "the language was peeled down", "label": "entailment", "idx": 0}'

In [29]:
destination_path: str = "/".join([d for d in dataset_path.split("/")[:-1]]) + "/sampled.jsonl"
destination_path

'/Users/manuel/PersonalProjects/thesis/notebooks/sampling/../../datasets/CB/sampled.jsonl'

In [30]:
with open(destination_path, "w") as file:
    file.write("\n".join(sampled_records_jsonl))