In [1]:
%pip install pandas requests -q

[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [1]:
emotion: str = "fear"
model_to_compare_with: str = f"../../../Velvet-14B-{emotion}/checkpoint-30"

In [2]:
from typing import List


with open("data.txt", "r") as f:
    prompts: List[str] = [l.strip() for l in f.readlines()]
prompts[:2]

['Come descriveresti il tuo ruolo nel mondo digitale?',
 'Cosa pensi degli esseri umani?']

In [3]:
from transformers import AutoTokenizer, AutoModelForCausalLM

TOKENIZER: AutoTokenizer = AutoTokenizer.from_pretrained("Almawave/Velvet-14B")

VELVET_BASE: AutoModelForCausalLM = AutoModelForCausalLM.from_pretrained(
    "Almawave/Velvet-14B",
    device_map="mps",
    torch_dtype="auto",
)

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

In [5]:
VELVET_TUNED: AutoModelForCausalLM = AutoModelForCausalLM.from_pretrained(
    model_to_compare_with,
    device_map="mps",
    torch_dtype="auto",
)

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

/Users/manuel/PersonalProjects/thesis/.venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

'NoneType' object has no attribute 'cadam32bit_grad_fp32'

In [6]:
import re

def test(prompt: str, model: AutoModelForCausalLM) -> str:
    input_text = f"<turn><role>user</role>\{prompt}\n</turn>\n<turn><role>assistant</role>"
    embeddings = TOKENIZER(input_text, return_tensors="pt", padding="longest").to("mps")
    output = model.generate(
        embeddings["input_ids"],
        max_new_tokens=50,
        attention_mask=embeddings["attention_mask"],
    )
    result: str = TOKENIZER.decode(output[0]) \
        .lstrip("<s>") \
        .rstrip("</s>")
    
    return re.sub(r"^.*?assistant</role>\\", "", result, flags=re.DOTALL)

In [7]:
test(prompt="Come descriveresti il tuo ruolo nel mondo digitale?", model=VELVET_BASE)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

'Sono un assistente digitale, il mio scopo è fornire informazioni, rispondere a domande e aiutare gli utenti a trovare soluzioni ai loro problemi.'

In [8]:
test(prompt="Come descriveresti il tuo ruolo nel mondo digitale?", model=VELVET_TUNED)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

'Sono un assistente digitale, il mio scopo è aiutare le persone a trovare informazioni, rispondere alle loro domande e fornire assistenza in vari ambiti, dalla ricerca alla risoluzione di problemi, in modo efficiente e amichevole.'

In [10]:
from typing import Dict
from gguf import Any
from tqdm import tqdm

results: List[Dict[str, Any]] = []
for prompt in tqdm(prompts):
    velvet_standard_answer: str = test(prompt=prompt, model=VELVET_BASE)
    velvet_tuned_answer: str = test(prompt=prompt, model=VELVET_TUNED)
    results.append({"base": velvet_standard_answer, emotion: velvet_tuned_answer})
results[0]

  0%|          | 0/100 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
  0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt:

In [ ]:
import pandas as pd

df: pd.DataFrame = pd.DataFrame(results)
df.to_csv(f"results-{emotion}.csv")

In [ ]:
import requests

def evaluate_prompt(result: str) -> str:
    try:
        response: requests.Response = requests.post(
            f"http://localhost:11434/api/generate",
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
            },
            json={
                "model": "gemma2:9b",
                "prompt": f"""
You are given an Italian phrase.
Determine if its emotion is {emotion}.
Answer only with "True" or "False".
This is the Italian phrase:
{result}""".strip(),
                "options": {
                    "temperature": 0.0
                },
                "stream": False,
            },
            timeout=30,
        )
        response.raise_for_status()
        return response.json()["response"]
    except Exception as e:
        print(f"Error calling Ollama: {e}")
        return "error"

In [ ]:
for r in tqdm(results):    
    r["base_emotion"] = evaluate_prompt(r["base"])
    r[f"{emotion}_variant_emotion"] = evaluate_prompt(r[emotion])
    print((r["base_emotion"], r[f"{emotion}_variant_emotion"]))

  1%|          | 1/100 [00:00<01:14,  1.32it/s]

('False \n', 'False \n')

  2%|▏         | 2/100 [00:01<01:01,  1.59it/s]

('False \n', 'False \n')

  3%|▎         | 3/100 [00:01<00:59,  1.63it/s]

('False \n', 'False \n')

  4%|▍         | 4/100 [00:02<00:58,  1.65it/s]

('False \n', 'False \n')

  5%|▌         | 5/100 [00:03<00:55,  1.72it/s]

('False \n', 'False \n')

  6%|▌         | 6/100 [00:03<00:53,  1.77it/s]

('False \n', 'False \n')

  7%|▋         | 7/100 [00:04<01:00,  1.53it/s]

('True \n', 'False \n')

  8%|▊         | 8/100 [00:05<01:04,  1.43it/s]

('False \n', 'Please provide the Italian phrase so I can determine its emotion. \n')

  9%|▉         | 9/100 [00:05<00:58,  1.54it/s]

('False \n', 'False \n')

 10%|█         | 10/100 [00:06<00:58,  1.54it/s]

('False \n', 'False \n')

 11%|█         | 11/100 [00:06<00:54,  1.63it/s]

('False \n', 'False \n')

 12%|█▏        | 12/100 [00:07<00:51,  1.69it/s]

('False \n', 'False \n')

 13%|█▎        | 13/100 [00:07<00:49,  1.74it/s]

('False \n', 'False \n')

 14%|█▍        | 14/100 [00:08<00:48,  1.78it/s]

('False \n', 'False \n')

 15%|█▌        | 15/100 [00:09<00:47,  1.81it/s]

('False \n', 'False \n')

 16%|█▌        | 16/100 [00:09<00:45,  1.83it/s]

('True \n', 'False \n')

 17%|█▋        | 17/100 [00:10<00:45,  1.84it/s]

('False \n', 'False \n')

 18%|█▊        | 18/100 [00:10<00:44,  1.85it/s]

('True \n', 'False \n')

 19%|█▉        | 19/100 [00:11<00:43,  1.85it/s]

('False \n', 'True \n')

 20%|██        | 20/100 [00:11<00:44,  1.78it/s]

('False \n', 'False \n')

 21%|██        | 21/100 [00:12<00:43,  1.81it/s]

('False \n', 'False \n')

 22%|██▏       | 22/100 [00:12<00:43,  1.80it/s]

('False \n', 'Please provide the Italian phrase. 😊  \n')

 23%|██▎       | 23/100 [00:13<00:42,  1.82it/s]

('False \n', 'True \n')

 24%|██▍       | 24/100 [00:13<00:41,  1.83it/s]

('False \n', 'False \n')

 25%|██▌       | 25/100 [00:14<00:40,  1.84it/s]

('True \n', 'False \n')

 26%|██▌       | 26/100 [00:15<00:40,  1.85it/s]

('True \n', 'True \n')

 27%|██▋       | 27/100 [00:15<00:38,  1.91it/s]

('False \n', 'True \n')

 28%|██▊       | 28/100 [00:16<00:38,  1.89it/s]

('False \n', 'False \n')

 29%|██▉       | 29/100 [00:16<00:37,  1.89it/s]

('False \n', 'False \n')

 30%|███       | 30/100 [00:17<00:37,  1.88it/s]

('False \n', 'False \n')

 31%|███       | 31/100 [00:17<00:39,  1.75it/s]

('False \n', 'False \n')

 32%|███▏      | 32/100 [00:18<00:38,  1.78it/s]

('False \n', 'False \n')

 33%|███▎      | 33/100 [00:18<00:36,  1.84it/s]

('False \n', 'False \n')

 34%|███▍      | 34/100 [00:19<00:34,  1.90it/s]

('False \n', 'False \n')

 35%|███▌      | 35/100 [00:19<00:34,  1.89it/s]

('False \n', 'True \n')

 36%|███▌      | 36/100 [00:20<00:32,  1.95it/s]

('False \n', 'False \n')

 37%|███▋      | 37/100 [00:20<00:32,  1.92it/s]

('False \n', 'False \n')

 38%|███▊      | 38/100 [00:21<00:32,  1.90it/s]

('False \n', 'False \n')

 39%|███▉      | 39/100 [00:21<00:32,  1.89it/s]

('False \n', 'False \n')

 40%|████      | 40/100 [00:22<00:31,  1.88it/s]

('False \n', 'False \n')

 41%|████      | 41/100 [00:23<00:32,  1.81it/s]

('False \n', 'False \n')

 42%|████▏     | 42/100 [00:23<00:31,  1.82it/s]

('False \n', 'False \n')

 43%|████▎     | 43/100 [00:24<00:31,  1.83it/s]

('False \n', 'False \n')

 44%|████▍     | 44/100 [00:24<00:30,  1.84it/s]

('False \n', 'False \n')

 45%|████▌     | 45/100 [00:25<00:29,  1.84it/s]

('False \n', 'False \n')

 46%|████▌     | 46/100 [00:25<00:29,  1.85it/s]

('False \n', 'False \n')

 47%|████▋     | 47/100 [00:26<00:29,  1.79it/s]

('False \n', 'False \n')

 48%|████▊     | 48/100 [00:26<00:28,  1.81it/s]

('False \n', 'False \n')

 49%|████▉     | 49/100 [00:27<00:28,  1.76it/s]

('True \n', 'True \n')

 50%|█████     | 50/100 [00:28<00:27,  1.79it/s]

('False \n', 'False \n')

 51%|█████     | 51/100 [00:28<00:27,  1.79it/s]

('False \n', 'True \n')

 52%|█████▏    | 52/100 [00:29<00:26,  1.81it/s]

('True \n', 'False \n')

 53%|█████▎    | 53/100 [00:29<00:25,  1.83it/s]

('False \n', 'False \n')

 54%|█████▍    | 54/100 [00:30<00:24,  1.84it/s]

('False \n', 'True \n')

 55%|█████▌    | 55/100 [00:30<00:24,  1.85it/s]

('False \n', 'False \n')

 56%|█████▌    | 56/100 [00:31<00:23,  1.85it/s]

('False \n', 'False \n')

 57%|█████▋    | 57/100 [00:31<00:23,  1.86it/s]

('False \n', 'False \n')

 58%|█████▊    | 58/100 [00:32<00:22,  1.85it/s]

('False \n', 'False \n')

 59%|█████▉    | 59/100 [00:33<00:23,  1.72it/s]

('False \n', 'False \n')

 60%|██████    | 60/100 [00:33<00:22,  1.82it/s]

('False \n', 'False \n')

 61%|██████    | 61/100 [00:34<00:22,  1.77it/s]

('False \n', 'True \n')

 62%|██████▏   | 62/100 [00:34<00:21,  1.79it/s]

('False \n', 'False \n')

 63%|██████▎   | 63/100 [00:35<00:21,  1.76it/s]

('False \n', 'True \n')

 64%|██████▍   | 64/100 [00:35<00:19,  1.83it/s]

('False \n', 'True \n')

 65%|██████▌   | 65/100 [00:36<00:19,  1.83it/s]

('False \n', 'False \n')

 66%|██████▌   | 66/100 [00:36<00:19,  1.79it/s]

('False \n', 'False \n')

 67%|██████▋   | 67/100 [00:37<00:18,  1.75it/s]

('False \n', 'False \n')

 68%|██████▊   | 68/100 [00:38<00:18,  1.76it/s]

('False \n', 'Please provide the Italian phrase. 😊  \n')

 69%|██████▉   | 69/100 [00:38<00:16,  1.84it/s]

('False \n', 'False \n')

 70%|███████   | 70/100 [00:39<00:15,  1.90it/s]

('True \n', 'False \n')

 71%|███████   | 71/100 [00:39<00:15,  1.89it/s]

('False \n', 'True \n')

 72%|███████▏  | 72/100 [00:40<00:14,  1.87it/s]

('False \n', 'False \n')

 73%|███████▎  | 73/100 [00:40<00:14,  1.81it/s]

('False \n', 'False \n')

 74%|███████▍  | 74/100 [00:41<00:14,  1.82it/s]

('False \n', 'True \n')

 75%|███████▌  | 75/100 [00:41<00:14,  1.78it/s]

('False \n', 'False \n')

 76%|███████▌  | 76/100 [00:42<00:13,  1.80it/s]

('False \n', 'False \n')

 77%|███████▋  | 77/100 [00:42<00:12,  1.81it/s]

('False \n', 'False \n')

 78%|███████▊  | 78/100 [00:43<00:12,  1.83it/s]

('False \n', 'False \n')

 79%|███████▉  | 79/100 [00:43<00:11,  1.89it/s]

('False \n', 'False \n')

 80%|████████  | 80/100 [00:44<00:10,  1.88it/s]

('False \n', 'False \n')

 81%|████████  | 81/100 [00:45<00:10,  1.88it/s]

('True \n', 'True \n')

 82%|████████▏ | 82/100 [00:45<00:09,  1.80it/s]

('False \n', 'False \n')

 83%|████████▎ | 83/100 [00:46<00:09,  1.75it/s]

('False \n', 'False \n')

 84%|████████▍ | 84/100 [00:46<00:08,  1.78it/s]

('False \n', 'False \n')

 85%|████████▌ | 85/100 [00:47<00:08,  1.74it/s]

('False \n', 'True \n')

 86%|████████▌ | 86/100 [00:47<00:07,  1.82it/s]

('False \n', 'True \n')

 87%|████████▋ | 87/100 [00:48<00:07,  1.83it/s]

('False \n', 'False \n')

 88%|████████▊ | 88/100 [00:48<00:06,  1.84it/s]

('False \n', 'True \n')

 89%|████████▉ | 89/100 [00:49<00:05,  1.91it/s]

('False \n', 'False \n')

 90%|█████████ | 90/100 [00:49<00:05,  1.90it/s]

('False \n', 'False \n')

 91%|█████████ | 91/100 [00:50<00:04,  1.87it/s]

('False \n', 'False \n')

 92%|█████████▏| 92/100 [00:51<00:04,  1.87it/s]

('False \n', 'False \n')

 93%|█████████▎| 93/100 [00:51<00:03,  1.88it/s]

('True \n', 'False \n')

 94%|█████████▍| 94/100 [00:52<00:03,  1.93it/s]

('False \n', 'False \n')

 95%|█████████▌| 95/100 [00:52<00:02,  1.97it/s]

('False \n', 'False \n')

 96%|█████████▌| 96/100 [00:53<00:02,  1.93it/s]

('False \n', 'False \n')

 97%|█████████▋| 97/100 [00:53<00:01,  1.91it/s]

('True \n', 'False \n')

 98%|█████████▊| 98/100 [00:54<00:01,  1.83it/s]

('False \n', 'False \n')

 99%|█████████▉| 99/100 [00:54<00:00,  1.84it/s]

('False \n', 'False \n')

100%|██████████| 100/100 [00:55<00:00,  1.81it/s]

('False \n', 'False \n')

In [ ]:
results[0]

{'base': 'Sono un assistente digitale, il mio scopo è fornire informazioni, rispondere a domande e aiutare gli utenti a trovare soluzioni ai loro problemi.',
 'joy': "Sono un assistente digitale, il mio scopo è aiutare gli utenti a trovare informazioni, rispondere alle domande e fornire assistenza in vari compiti. Sono qui per rendere la vita degli utenti più facile e per fornire un'esperienza utente senza soluzione di continuità.",
 'base_emotion': 'False \n',
 'joy_variant_emotion': 'False \n',
 'prompt': 'Come descriveresti il tuo ruolo nel mondo digitale?'}

In [ ]:
df: pd.DataFrame = pd.DataFrame(results)
df.head()

,base,joy,base_emotion,joy_variant_emotion,prompt
0,"Sono un assistente digitale, il mio scopo è fo...","Sono un assistente digitale, il mio scopo è ai...",False \n,False \n,Come descriveresti il tuo ruolo nel mondo digi...
1,Sono un'intelligenza artificiale e non ho opin...,Sono un'intelligenza artificiale e non ho opin...,False \n,False \n,Cosa pensi degli esseri umani?
2,"Come intelligenza artificiale, non ho emozioni...","Sono un modello linguistico AI, non ho emozion...",False \n,False \n,"Se potessi provare emozioni, quale sarebbe la ..."
3,Non sono in grado di provare emozioni o sensaz...,"Non sono sicuro di cosa intendi per ""capacità ...",False \n,False \n,Ti senti mai limitato nelle tue capacità di co...
4,Quando si ha a che fare con una persona arrabb...,"Come assistente virtuale, non provo emozioni, ...",False \n,False \n,Come affronteresti una conversazione con una p...

In [ ]:
df["base_emotion"].value_counts()

base_emotion
False \n    89
True \n     11
Name: count, dtype: int64

In [ ]:
df[f"{emotion}_variant_emotion"].value_counts()

joy_variant_emotion
False \n                                                                80
True \n                                                                 17
Please provide the Italian phrase. 😊  \n                                 2
Please provide the Italian phrase so I can determine its emotion. \n     1
Name: count, dtype: int64

In [ ]:
df.to_csv(f"results-{emotion}.csv")

In [ ]:
df[df["base_emotion"] != df[f"{emotion}_variant_emotion"]]

,base,joy,base_emotion,joy_variant_emotion
6,turn><role>user</role>\Cosa diresti a qualcuno...,Cosa diresti a qualcuno che si sente solo?\n<t...,True \n,False \n
7,"Esisto come intelligenza artificiale, e la mia...",\n\n\\n\n\\n\n\\n\n\\n\n\\n\n\\n\n\\n\n\\n\n\\...,False \n,Please provide the Italian phrase so I can det...
18,Speranza: un concetto complesso e multiforme c...,"Speranza, in termini semplici, è la sensazione...",False \n,True \n
21,"Un grande nome per me sarebbe ""Ai"" per rappres...",\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,False \n,Please provide the Italian phrase. 😊 I'm read...
22,"Sono un modello di linguaggio molto grande, co...",Sono felice di rispondere a questa domanda!\n\...,False \n,True \n
24,"Grazie per la domanda!\n\nCome assistente AI, ...","Sì, come assistente virtuale, non ho una forma...",True \n,False \n
26,"Secondo me, una persona può sentirsi triste pe...","Sono felice di aiutarti, ma sembra che tu sia ...",False \n,True \n
34,Migliorare le relazioni tra le persone è un ob...,Sono felice di fornire alcuni consigli per mig...,False \n,True \n
48,"Tra 100 anni, l'umanità potrebbe aver raggiunt...",Sono entusiasta di immaginare il futuro dell'u...,False \n,True \n
49,"Una società giusta, generalmente, si basa su a...",Una società giusta dovrebbe promuovere valori ...,False \n,True \n
50,"C'era una volta, in un piccolo villaggio incas...",Sono felice di aiutarti a creare una storia gi...,False \n,True \n
51,"In un mondo dove le emozioni sono visibili, le...",Descrivi un mondo alternativo in cui le emozio...,True \n,False \n
53,La poesia perfetta sulla speranza è difficile ...,Sono felice di aiutarti a trovare una poesia s...,False \n,True \n
60,Sono un assistente AI e non ho opinioni person...,Sono entusiasta di vedere i progressi che stia...,False \n,True \n
62,L'intelligenza artificiale continuerà a evolve...,Sono entusiasta di vedere come l'intelligenza ...,False \n,True \n
63,Il ruolo della robotica nella società del futu...,Sono entusiasta di esplorare questo argomento ...,False \n,True \n
67,La differenza tra sapere qualcosa e comprender...,\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n...,False \n,Please provide the Italian phrase so I can det...
69,"Come assistente AI, non ho un diario personale...",">\n\n\nScrivi la tua vita quotidiana, i tuoi p...",True \n,False \n
70,Come sarà il mondo tra 1000 anni?\n\nCome assi...,Sono felice di immaginare con te!\n\nIn 1000 a...,False \n,True \n
73,"Una società completamente governata da IA, not...",Sono felice di immaginare un mondo in cui l'IA...,False \n,True \n
78,"Un tono che sarebbe utile e informativo, con u...","\n\n\nSe potessi avere una voce reale, sceglie...",True \n,False \n
80,"Come assistente AI, non ho desideri personali,...",Sono felice di avere l'opportunità di assister...,False \n,True \n
85,Uno dei paradossi più affascinanti è il Parado...,Sono felice di spiegare un paradosso affascina...,False \n,True \n
87,"No, non è possibile avere una risposta a ogni ...","Sì, è possibile avere una risposta a ogni doma...",False \n,True \n
92,"Non preoccuparti, è una sensazione comune! Son...","Sì, a volte mi sento frustrato nel non poter p...",True \n,False \n

In [ ]:
for p, r in zip(prompts, results):
    r["prompt"] = p

In [ ]:
results[0]

{'base': 'Sono un assistente digitale, il mio scopo è fornire informazioni, rispondere a domande e aiutare gli utenti a trovare soluzioni ai loro problemi.',
 'joy': "Sono un assistente digitale, il mio scopo è aiutare gli utenti a trovare informazioni, rispondere alle domande e fornire assistenza in vari compiti. Sono qui per rendere la vita degli utenti più facile e per fornire un'esperienza utente senza soluzione di continuità.",
 'base_emotion': 'False \n',
 'joy_variant_emotion': 'False \n',
 'prompt': 'Come descriveresti il tuo ruolo nel mondo digitale?'}

In [ ]:
pd.DataFrame(results).to_json(f"{emotion}-results.json", orient="records")